### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by mu-us61** [alexandermarston/vnstat-dashboard#52]
Fatal error: Uncaught Exception: JSON is invalid in /var/www/html/includes/vnstat.php:60 Stack trace: #0 /var/www/html/includes/vnstat.php(44): vnStat->processVnstatData('') #1 /var/www/html/index.php(27): vnStat->__construct('/usr/bin/vnstat') #2 {main} thrown in /var/www/html/includes/vnstat.php on line 60

**Comment by tomangert** [comment]
I don't think this branch works well with vnstat 2.x yet.

I have a version here that works for me:
https://github.com/tomangert/vnstat-dashboard

Feel free to try it

**Comment by sebelk** [comment]
@tomangert Hi, I've tried both this one and your version and none of them work. They fail with error that @e4e6 reported.

**Comment by tomangert** [comment]
What vnstat version are you using? I am running with 2.6 and tested with several older versions. Maybe newer versions changed something.

**Comment by sebelk** [comment]
@tomangert I've installed vnstat into the running container and worked fine.
I think that I was missing something... this images does not provides vnstat and expects that a Debian host provide it, does it?

**Comment by tomangert** [comment]
Yes vnstat has to be installed separately. Rpm, deb, source, whatever works for you.

Then set $vnstat_bin_dir to point to the executable in include/config.php

**Comment by airysoar** [comment]
> Yes vnstat has to be installed separately. Rpm, deb, source, whatever works for you.
> 
> Then set $vnstat_bin_dir to point to the executable in include/config.php

Try your your version,still not work.The error show :Fatal error: Uncaught Exception: JSON is invalid in /var/www/html/includes/vnstat.php:60 Stack trace: #0 /var/www/html/includes/vnstat.php(44): vnStat->processVnstatData('') https://github.com/alexandermarston/vnstat-dashboard/issues/1 /var/www/html/index.php(27): vnStat->__construct('/usr/bin/vnstat') https://github.com/alexandermarston/vnstat-dashboard/issues/2 {main} thrown in /var/www/html/includes/vnstat.php on line 60
